import { PrismaClient, type Prisma } from "@prisma/client";

const prisma = new PrismaClient();

type ReasonSeed = Pick<
  Prisma.RecommendationReasonCreateManyInput,
  "id" | "label" | "category" | "genreKey" | "sortOrder" | "active" | "spoilerRisk" | "familySafe"
>;

const globalReasons = [
  "Amazing characters",
  "Beautifully made",
  "Great story",
  "Fast-paced",
  "Slow burn",
  "Hilarious",
  "Tear jerker",
  "Mindbending",
  "Brutal",
  "Uplifting",
  "Visually stunning",
  "Great soundtrack",
  "Comfort watch",
  "Cult classic",
  "Great to watch with the kids",
  "Worth discussing afterwards",
  "Weird but brilliant",
  "Gripping from the start",
  "Atmospheric",
  "Easy watch",
];

const genreReasons: Record<string, string[]> = {
  action: [
    "Fast-paced",
    "Brutal",
    "Great set pieces",
    "Pure adrenaline",
    "Tense",
    "Explosive",
    "Great fight scenes",
    "High stakes",
    "Gripping from the start",
    "Visually spectacular",
    "Lean and punchy",
    "Big-screen energy",
    "Relentless",
    "Surprisingly emotional",
    "Fun escapism",
  ],
  adventure: [
    "Big journey",
    "Great sense of wonder",
    "Fun escapism",
    "Visually stunning",
    "Great to watch with the kids",
    "Sweeping",
    "Imaginative world",
    "Feel-good",
    "Exciting",
    "Charming",
    "Big-hearted",
    "Great locations",
    "Family-friendly",
    "Epic scale",
    "Pure adventure",
  ],
  animation: [
    "Great to watch with the kids",
    "Beautiful animation",
    "Hilarious",
    "Big-hearted",
    "Visually inventive",
    "Comfort watch",
    "Surprisingly emotional",
    "Great characters",
    "Family-friendly",
    "Clever",
    "Charming",
    "Feel-good",
    "Great soundtrack",
    "Imaginative world",
    "Rewatchable",
  ],
  comedy: [
    "Hilarious",
    "Easy watch",
    "Great characters",
    "Sharp writing",
    "Feel-good",
    "Comfort watch",
    "Absurd",
    "Clever",
    "Quotable",
    "Great cast",
    "Chaotic fun",
    "Darkly funny",
    "Awkward in a good way",
    "Rewatchable",
    "Light and breezy",
  ],
  crime: [
    "Gripping",
    "Tense",
    "Brutal",
    "Smart plotting",
    "Great characters",
    "Atmospheric",
    "Dark",
    "Slow burn",
    "Morally murky",
    "Stylish",
    "Gritty",
    "Great dialogue",
    "High stakes",
    "Worth discussing afterwards",
    "Hard-boiled",
  ],
  documentary: [
    "Fascinating",
    "Eye-opening",
    "Worth discussing afterwards",
    "Moving",
    "Shocking but not exploitative",
    "Informative",
    "Inspiring",
    "Strange but true",
    "Important story",
    "Human",
    "Thought-provoking",
    "Well researched",
    "Unusual subject",
    "Gripping real story",
    "Stays with you",
  ],
  drama: [
    "Amazing characters",
    "Great performances",
    "Emotional",
    "Slow burn",
    "Beautifully made",
    "Tear jerker",
    "Thought-provoking",
    "Quietly powerful",
    "Human",
    "Great writing",
    "Worth discussing afterwards",
    "Melancholy",
    "Intimate",
    "Subtle",
    "Stays with you",
  ],
  family: [
    "Great to watch with the kids",
    "Family-friendly",
    "Comfort watch",
    "Feel-good",
    "Big-hearted",
    "Charming",
    "Funny for all ages",
    "Gentle",
    "Rewatchable",
    "Uplifting",
    "Great message",
    "Magical",
    "Easy watch",
    "Colourful",
    "Cosy",
  ],
  fantasy: [
    "Imaginative world",
    "Magical",
    "Visually stunning",
    "Big adventure",
    "Epic scale",
    "Strange and beautiful",
    "Great mythology",
    "Escapist",
    "Atmospheric",
    "Great creatures",
    "Dark fantasy",
    "Dreamlike",
    "Family-friendly",
    "Cult classic",
    "Weird but brilliant",
  ],
  horror: [
    "Scary",
    "Creepy",
    "Brutal",
    "Atmospheric",
    "Tense",
    "Slow burn",
    "Disturbing",
    "Weird but brilliant",
    "Stylish",
    "Great creature design",
    "Psychological",
    "Claustrophobic",
    "Darkly funny",
    "Cult classic",
    "Stays with you",
  ],
  mystery: [
    "Intriguing",
    "Gripping",
    "Smart plotting",
    "Atmospheric",
    "Tense",
    "Slow burn",
    "Mindbending",
    "Great clues",
    "Worth discussing afterwards",
    "Stylish",
    "Unsettling",
    "Clever",
    "Dark",
    "Keeps you guessing",
    "Satisfying mystery",
  ],
  romance: [
    "Romantic",
    "Charming",
    "Emotional",
    "Bittersweet",
    "Great chemistry",
    "Feel-good",
    "Tear jerker",
    "Comfort watch",
    "Beautifully made",
    "Funny and warm",
    "Gentle",
    "Heartbreaking",
    "Rewatchable",
    "Great dialogue",
    "Cosy",
  ],
  "science-fiction": [
    "Mindbending",
    "Big ideas",
    "Visually stunning",
    "Thought-provoking",
    "Atmospheric",
    "Strange but brilliant",
    "Futuristic",
    "Dystopian",
    "Smart",
    "Great world-building",
    "Tense",
    "Worth discussing afterwards",
    "Philosophical",
    "Dark",
    "Cult classic",
  ],
  thriller: [
    "Tense",
    "Gripping",
    "Fast-paced",
    "Slow burn",
    "High stakes",
    "Unsettling",
    "Atmospheric",
    "Smart plotting",
    "Claustrophobic",
    "Paranoid",
    "Dark",
    "Brutal",
    "Stylish",
    "Lean and punchy",
    "Edge-of-seat",
  ],
  war: [
    "Brutal",
    "Powerful",
    "Harrowing",
    "Tense",
    "Epic scale",
    "Human",
    "Thought-provoking",
    "Visually stunning",
    "Great performances",
    "Historically interesting",
    "Emotionally heavy",
    "Worth discussing afterwards",
    "Gripping",
    "Anti-war",
    "Stays with you",
  ],
  history: [
    "Historically interesting",
    "Powerful",
    "Great performances",
    "Thought-provoking",
    "Beautifully made",
    "Human",
    "Epic scale",
    "Worth discussing afterwards",
    "Emotional",
    "Gripping",
  ],
  music: [
    "Great soundtrack",
    "Amazing performances",
    "Joyful",
    "Emotional",
    "Fascinating",
    "Beautifully made",
    "Great energy",
    "Inspiring",
    "Rewatchable",
    "Worth discussing afterwards",
  ],
  western: [
    "Atmospheric",
    "Gritty",
    "Slow burn",
    "Epic landscape",
    "Morally murky",
    "Great characters",
    "Brutal",
    "Stylish",
    "Classic feel",
    "Tense",
  ],
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildReasonSeeds(): ReasonSeed[] {
  const globalSeeds = globalReasons.map((label, index) => ({
    id: `global-${slugify(label)}`,
    label,
    category: "global",
    genreKey: null,
    sortOrder: index + 1,
    active: true,
    spoilerRisk: "low" as const,
    familySafe: label !== "Brutal",
  }));

  const genreSeeds = Object.entries(genreReasons).flatMap(([genreKey, labels]) =>
    labels.map((label, index) => ({
      id: `${genreKey}-${slugify(label)}`,
      label,
      category: "genre",
      genreKey,
      sortOrder: index + 1,
      active: true,
      spoilerRisk: "low" as const,
      familySafe: !["Brutal", "Disturbing", "Harrowing"].includes(label),
    })),
  );

  return [...globalSeeds, ...genreSeeds];
}

async function main() {
  const reasons = buildReasonSeeds();

  await prisma.recommendationReason.createMany({
    data: reasons,
    skipDuplicates: true,
  });

  console.log(`Seeded ${reasons.length} recommendation reason chips.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
